### PR TITLE
Add Tooltip Text when Exporting Project & UI Improvement

### PR DESCRIPTION
**Pull request by hansheng000512**
# Description

- Changed button color to blue.
- Added tooltip text when exporting project.
- Improve Alignment

Fixes # (issue)

Loading Spinner:

Export Project:

Tooltip Text for Export Modal

Create New Project

Rename Project

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] UI Improvement

# Tested on?

- [x] Windows  
- [ ] Linux Ubuntu 
- [ ] Centos 
- [ ] Mac  
- [ ] Others  (State here -> xxx )  

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged

### CODE REVIEW

**Review by amalsyahmi-certifai — DISMISSED** [review]

**Comment by hansheng000512** [comment]
Increase Advanced Setting Text Font Size:

**Comment by hansheng000512** [comment]
Rename Success Modal

**Review by codenamewei — CHANGES_REQUESTED** [review]
Looking good. 



Require changes to the indication text in here

Screenshot 2021-06-09 at 8 57 50 AM

```
Config File is a JSON file generated by Classifai.
The file contains metadata of a project and can be retrieved using export project function.
```


Another indication text to add is on the label file , but that pending PR from https://github.com/CertifaiAI/Classifai_FrontEnd/pull/166 to merge first, 
If i imagine the position, will be right under Label File (Optional):

image


```
What is Label File?

Label file is TXT file generated by Classifai. 
The file facilitate labels of the right order and capitalization being used across multiple projects.
It can be retrieved using export labels function.
```

Due to there's still pending item to be complete in https://github.com/CertifaiAI/Classifai_FrontEnd/pull/166, 
I suggest to keep this PR open for the moment and only pull in latest to work on when that PR is merged.

Thanks

**Comment by hansheng000512** [comment]
Create Project Tooltip:
Capture

Import Config File Tooltip:
Capture

**Comment by hansheng000512** [comment]
@codenamewei @amalsyahmi-certifai 
I will improve the UI/Alignment for Export Project Popup Modal in next PR.

**Review by codenamewei — CHANGES_REQUESTED** [review]
Can we do a justify of the line so text of the same length? 
Note: do advice me if its not doable

attaching below for reference

google-drive-docs-justify


Also prefer **a new blank line** in the following check point

meaning

```
This is the first paragraph.
[a blank line]
This is the second paragraph.
```
121499203-be3e3480-ca0f-11eb-985d-6dd8ddfb8068


121499368-e62d9800-ca0f-11eb-8b90-929ccf303338

**Comment by hansheng000512** [comment]
Tooltip Alignment:
Capture

Capture

**Comment by hansheng000512** [comment]
Export Project:


https://user-images.githubusercontent.com/81958029/121629750-70c4d480-caae-11eb-9bca-f766565dde07.mp4

**Review by amalsyahmi-certifai — COMMENTED** [review]
In my opinion, I'm little bit confused with the color usage of selection buttons and submit button.
When the user click one of the option, the other option's background color is same as submit button background color, and for me it looks like the other option is selected instead of what the user clicked.
These are my suggestions:

1
Selected button - border color: blue, bg color: blue, text color: white
Unselected button - border color: white, bg color: transparent, text color: white

https://user-images.githubusercontent.com/76939137/121632886-61e12080-cab4-11eb-9627-5109c07b94f1.mp4


2
Selected button - border color: blue, bg color: blue, text color: white
Unselected button - border color: blue, bg color: transparent, text color: blue

https://user-images.githubusercontent.com/76939137/121633040-b389ab00-cab4-11eb-8d14-ba1627bc5be0.mp4

**Comment by codenamewei** [comment]
For export project , 

if i imagine it , it will be of this format + create button at the bottom, excluding the "choose the right export"
Capture (2)




where the text just show when the icon is click just like import project and label file 

```
Choosing the right export:
(a blank line)
Config File is the configuration file contains of metadata of a project. It is suitable when the data is readily available in the system to be imported to. 
(a blank line)
Zip File contains the Config File with dataset used in a project. It compiles all the components of a project to be reproduced in a different system.
```


Reason we want to hide the text is for minimalism, meaning people who already know what they want to export dont need to see the text 


is there any difficulty in implementing that? 

@hansheng000512

**Comment by codenamewei** [comment]
> In my opinion, I'm little bit confused with the color usage of selection buttons and submit button.
> When the user click one of the option, the other option's background color is same as submit button background color, and for me it looks like the other option is selected instead of what the user clicked.
> These are my suggestions:
> 
> 1
> Selected button - border color: blue, bg color: blue, text color: white
> Unselected button - border color: white, bg color: transparent, text color: white
> 
>  2021-06-11.12-44-54.mp4 
> 2
> Selected button - border color: blue, bg color: blue, text color: white
> Unselected button - border color: blue, bg color: transparent, text color: blue
> 
>  2021-06-11.12-47-11.mp4

im also very much confused by **the current selection** due to the color

in my personal perspective, i will imagine the color same with the confirm button is the one of my current choice

Screenshot 2021-06-11 at 1 03 17 PM

**Comment by hansheng000512** [comment]
Export Project:

https://user-images.githubusercontent.com/81958029/121643967-03706e00-cac5-11eb-9598-e86c557d3f7a.mov

**Review by codenamewei — APPROVED** [review]
okay from my side in terms of functionality.

**Pull request merged**
