### PR TITLE
Add guiding cross line, add delete project confirmation, fix undo-redo button & fix grammar

### PR DESCRIPTION
**Pull request by amalsyahmi-certifai**
# Description

- Add guiding cross line for more effective bounding box labelling.

https://user-images.githubusercontent.com/76939137/127118181-f5ab87cc-4c4b-4801-9db9-e84d7e1d12ba.mp4

- Fix undo redo button that doesn't work previously.

- Fix grammar (is -> was).

image

- Ask user confirmation when user want to delete a project.

image

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Tested on?

- [x] Windows  
- [ ] Linux Ubuntu 
- [ ] Centos 
- [ ] Mac  
- [ ] Others  (State here -> xxx )  

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged

### CODE REVIEW

**Comment by amalsyahmi-certifai** [comment]
Please ignore failed code analysis. Will fixed in the next PR in code-refactoring branch

**Review by hansheng0512 — CHANGES_REQUESTED** [review]
Suggest to use other color because the bbox color are in yellow already.
Capture

**Comment by devenyantis** [comment]
> Suggest to use other color because the bbox color are in yellow already.
> Capture

yes. agree with this. And the thickness can be reduced as well. 
For image with lots of annotation, can look messy.

**Comment by amalsyahmi-certifai** [comment]
@hansheng0512 @devenyantis 
**Changes:**
- Change guiding lines color from yellow to red (Classifai color code).
- Add toggle button to switch on and off the guiding lines.

https://user-images.githubusercontent.com/76939137/127425822-cf2c8868-319a-4d9a-8c41-c5d55c20743a.mp4

**Review by hansheng0512 — APPROVED** [review]
Looks good to me

**Comment by devenyantis** [comment]
> @hansheng0512 @devenyantis
> **Changes:**
> 
> * Change guiding lines color from yellow to red (Classifai color code).
> * Add toggle button to switch on and off the guiding lines.
> 
>  2021-07-29.11-11-38.mp4

Nice.
I think the toggle button should be under the bounding box.

**Review by devenyantis — CHANGES_REQUESTED** [review]
I think the toggle button should be under the bounding box. So it will be close to the bounding box button. And want to keep the info at the end.

**Comment by amalsyahmi-certifai** [comment]
Changes:
- Change position of toggle button under the bounding box button.

**Review by devenyantis — APPROVED** [review]

**Pull request merged**
