### PR TITLE
Improving create new project flow

### PR DESCRIPTION
**Pull request by amalsyahmi-certifai**
# Description

Change create new project flow to be more user friendly.

- Before: 
  - Fill in project name
  - Choose label list file (optional)
  - Click Create
  - Choose project folder 

- After:
  - Fill in project name
  - Choose project folder
  - Choose label list file (optional)
  - Click Create

https://user-images.githubusercontent.com/76939137/120786815-3d8bbe00-c561-11eb-8cf6-a23f8b533015.mp4

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Tested on?

- [x] Windows  
- [ ] Linux Ubuntu 
- [ ] Centos 
- [ ] Mac  
- [ ] Others  (State here -> xxx )  

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged

### CODE REVIEW

**Comment by codenamewei** [comment]
hi @amalsyahmi-certifai , 

it looks great. 

can we do an experiment to see how it looks like when the distance of 1 and 2 is the same?

Screenshot 2021-06-08 at 1 28 27 AM


Requesting to see if current design if differences in vertical gap is better or same gap distance is better

**Comment by amalsyahmi-certifai** [comment]
@codenamewei 
I think this looks better.

image

**Review by codenamewei — CHANGES_REQUESTED** [review]
as per comment

**Comment by codenamewei** [comment]
> @codenamewei
> I think this looks better.
> 
> image

yeah.....agree with you

i will re-request changes on this PR and if you make the changes, kindly click that again

Screenshot 2021-06-08 at 9 36 07 AM

**Comment by codenamewei** [comment]
working on backend changes. will merge when check on backend all things working fine.

**Comment by codenamewei** [comment]
image a
Screenshot 2021-06-08 at 12 19 52 PM

image b
Screenshot 2021-06-08 at 12 19 31 PM


3 observations i saw
1. from image a -> image b, the gap seems to change when input is put in

   - to be specific, the gap between project name and project folder seems to be more narrow after click on **choose folder**
   - the gap between create button and background window also seems to bigger after insertion
   
2. for **new project name**, suggest to do 
```
New 
Project Name:
```

or only Project Name (cause we can expect it be new project from the title of the window - **Create New Project**
```
Project Name: 
```

3. the alignment of project folder - **Agriculture** and label file **man_label.txt** is off, I dont have the best suggestion as of now...but can we try left incline to see if its better?
Another option is try to align it toward the line of beginning of letter **C** of Choose Folder / Choose File

@amalsyahmi-certifai

**Comment by amalsyahmi-certifai** [comment]
Fix/ changes:
- Fix gap issues
- Change 'New Project Name' to 'Project Name'
- Align folder/file name with text in button.

image

**Comment by codenamewei** [comment]
work as intended, i will continue to work on backend development before proceed with merging this

would also like to see if during the process if i found out any problems. thanks amal

**Comment by amalsyahmi-certifai** [comment]
@codenamewei 
Done reflect changes on frontend.

**Comment by codenamewei** [comment]
> @codenamewei
> Done reflect changes on frontend.

thanks! checking on it

**Review by codenamewei — CHANGES_REQUESTED** [review]
Hi @amalsyahmi-certifai 

Pretty sure this is the last one need changes (finger-crossed)

I missed out API reloadstatus

detailed changes are in the newest comment in the gist below
https://gist.github.com/codenamewei/19451f379a5efe29edab3c64c0a7c879


thank you

**Review by codenamewei — APPROVED** [review]
Backend code and compiled frontend code has been merged.

Foresee other bugs. Merging this to kick the balls moving. 

👍

**Pull request merged**
