### PR TITLE
🎇 Add in tutorial list

### PR DESCRIPTION
**Pull request by ken479**
# Description

tutorial_list

Tutorial list added for user reference. 

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Tested on?

- [x] Windows  
- [ ] Linux Ubuntu 
- [ ] Centos 
- [ ] Mac  
- [ ] Others  (State here -> xxx )  

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged

### CODE REVIEW

**Comment by devenyantis** [comment]
image

The writing is overflowing.

**Comment by ken479** [comment]
> image
> 
> The writing is overflowing.

@devenyantis Interesting, I will try to check out the bug

**Comment by ken479** [comment]
@devenyantis adjusted the container size, try to see if the overflowing problem still persist

**Comment by devenyantis** [comment]
image
It's not centered. Maybe a few pointer to help.

image

I think that is because you wrap the string by itself with this div. So, it will place the text according to the position in the box. Which is centered horizontal only. 

Probably, few ways to solve it is use heading tag and apply css to center it OR very simple way is not to hard code the height of  the box.

**Comment by ken479** [comment]
@devenyantis Hi, I have made the height and width dynamic, please try it

**Comment by devenyantis** [comment]
image
It seems like you only change height to min-height. No change on my side still not centered vertically.

**Comment by ken479** [comment]
@devenyantis I added vertical align, see if it fix the issue

**Review by devenyantis — APPROVED** [review]

**Pull request merged**
