### PR TITLE
🎇 Features Factoring to Segmentation Module and Fixing Bugs

### PR DESCRIPTION
**Pull request by hansheng0512**
# Description

Features Refactoring and Bug Fixes.

Fixes # (issue)
- Sublabel Modal UI Adjustment
- Showing sublabel list in sublabel modal
- Allowing dblclick and enter key to complete polygon
- Undo Redo Fixing
- Fix Segmentation COCO output
- Fix Segmentation Json output

https://user-images.githubusercontent.com/81958029/127985741-2c6efe2d-f494-4a0b-8a20-608a1e37467a.mp4

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Tested on?

- [x] Windows  
- [ ] Linux Ubuntu 
- [ ] Centos 
- [ ] Mac  
- [ ] Others  (State here -> xxx )  

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged

### CODE REVIEW

**Review by amalsyahmi-certifai — APPROVED** [review]
Works as expected.

**Comment by hansheng0512** [comment]
Backend Branch: https://github.com/CertifaiAI/classifai/tree/deven_fix_fileSize

**Review by devenyantis — CHANGES_REQUESTED** [review]
Exported annotation have problem. Need to fix

**Review by devenyantis — APPROVED** [review]
Working for me.

**Pull request merged**
