### PR TITLE
Invalid project path and unsupported image format

### PR DESCRIPTION
**Pull request by amalsyahmi-certifai**
# Description

Classifai branch: https://github.com/CertifaiAI/classifai/tree/sum_v2a_folderFileValidation

Changes:
- Show invalid path status on project card, if the project path is invalid (project folder doesn't exist / has been moved).

image

- Show alert modal to the user if there are unsupported images included during create project and reload project.

https://user-images.githubusercontent.com/76939137/122342235-f77a2580-cf76-11eb-865a-b9d7b2345614.mp4

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Tested on?

- [x] Windows  
- [ ] Linux Ubuntu 
- [ ] Centos 
- [ ] Mac  
- [ ] Others  (State here -> xxx )  

# Checklist:

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged

### CODE REVIEW

**Comment by YCCertifai** [comment]
there's a small problem in the txt file.
some files are separated by newline, some are separated by commas
image

**Comment by YCCertifai** [comment]
image
About the prompt message.
The title could be: 
```Unsupported Image Found!```
The message could be: 
```
There are <n> unsupported images included in the project!  
The list of images is in the downloaded TXT file.
Kindly convert them to jpg/png type and reimport them again
```

**Comment by YCCertifai** [comment]
the link provided in the pop up message will be refined.
Screenshots and step-by-step walkthrough will be included after everything is finalized

**Review by YCCertifai — CHANGES_REQUESTED** [review]
there's a small problem in the txt file.
some files are separated by newline, some are separated by commas
image

**Review by YCCertifai — CHANGES_REQUESTED** [review]
image
About the prompt message.
The title could be: 
```Unsupported Image Found!```
The message could be: 
```
There are <n> unsupported images included in the project!  
The list of images is in the downloaded TXT file.
Kindly convert them to jpg/png type and reimport them again.
```

**Review by YCCertifai — APPROVED** [review]

**Comment by amalsyahmi-certifai** [comment]
Changes:
- Display project path on project card in dataset management page
- Disable invalid path project.

**Comment by devenyantis** [comment]
Nice. Works from my side. 

> Changes:
> 
> * Display project path on project card in dataset management page
> * Disable invalid path project.

Works on Windows

**Review by codenamewei — APPROVED** [review]
Perfect

**Pull request merged**
